#spring:
#  application:
#    name: user-service
#    
#server:
#  port: 8081
##  port: 8082
#
#eureka:
#  client:
#    service-url:
##      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
#       defaultZone: http://localhost:8761/eureka/
       
spring:
  application:
    name: provider-user

server:
  port: 8762
#  port: 8763
#server:
#  port: 0 # 随机产生服务端口，避免在本地单机模拟集群时，反复手动修改不同的服务端口号的行为

eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.int} # 利用应用名加随机数的方式来区分不同的实例，从而实现在同一个主机上，不手动指定端口就能轻松启动多个实例的效果
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      


      