#spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: raw-sensor-data
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: beamofsoul
#    password: 91297918