server:
  port: 2222
  
spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true # 由于当前应用为注册中心，所以设置为false，代表不向注册中心注册自己
    fetch-registry: true # 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone: http://peer1:1111/eureka/
  instance:
    hostname: peer2