spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: localhost
    port: 5672
    username: beamofsoul
    password: 91297918
  datasource:
#    schema:
#      - classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: 
    continue-on-error: true
    initialize: true
    
server:
  port: 9411
  
#zipkin:
#  storage:
#    type: mysql