server:
  port: 8989

management:
  port: 8990
  
spring:
  application:
    name: turbine
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
turbine:
  app-config: ribbon-consumer-user  # 指定需要收集监控信息的服务名
  cluster-name-expression: new String("default") # 集群名称，当服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群，同时该参数可以在Hystrix仪表盘中用来定位不同的聚合集群，只需在Hystrix Stream的URL中通过cluster参数来指定
  combine-host-port: true # 可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计，默认值为true