server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 由于当前应用为注册中心，所以设置为false，代表不向注册中心注册自己
    fetch-registry: false # 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-self-preservation: false # 关闭自我保护，以防止关闭的实例无法被服务注册中心剔除的问题
    
#spring:
#  profiles:
#    active: peer1
#    active: peer2