spring:
  application:
    name: api-gateway
    
server:
  port: 8769
  
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: provider-user
    api-b:
      path: /api-b/**
      serviceId: feign-consumer-user
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/